name: After merge

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types:
      - closed

jobs:
  coverage_badge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        # skip aws-cli as is already included in github actions
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch anybadge awscli
      - name: Run coverage
        run: |
          hatch run cov
      - name: Create coverage files
        run: |
          cov_metric=$(hatch run coverage report --format=total)
          anybadge --overwrite --label="🎯 coverage" --value=$cov_metric --file=coverage.svg
          echo $cov_metric >> coverage.txt
      - name: Create coverage html report
        run: |
          hatch run coverage html -d htmlcov
      - name: Upload Coverage
        # do not upload using --key with .svg extension
        # notice that uploading the coverage html report may make the code public
        run: |
          aws s3api put-object --bucket zapy --key coverage-badge --body coverage.svg --content-type image/svg+xml
          aws s3api put-object --bucket zapy --key coverage-txt --body coverage.txt --content-type text/plain
          aws s3 sync htmlcov s3://zapy/htmlcov --delete
        env:
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
